### ISSUE TITLE
Error: The configmap "aws-auth" does not exist on terraform apply

### ISSUE THREAD

**Issue by neeri21** [EylonT/eks-wordpress#1]
Hi, I was following the instructions in the readme, and while i was running terraform apply, i got the error below.  Please help.

**Error: The configmap "aws-auth" does not exist**

with module.eks.kubernetes_config_map_v1_data.aws_auth[0],
on .terraform\modules\eks\main.tf line 555, in resource "kubernetes_config_map_v1_data" "aws_auth":
555: resource "kubernetes_config_map_v1_data" "aws_auth" {

Releasing state lock. This may take a few moments...

**Comment by EylonT** [comment]
Hi,

Thank you for the feedback.
Since this is a personal side project I didn't touch it in a while.
I did get back to it recently and faced the same issue due to changes in how EKS authentication works and thus changes in the official EKS module which generated the error. I modernized the project which is now working as expected.
Please give it another try.
